import { nomeModelo } from '../camisasCatalog';
const brl=v=>Number(v||0).toFixed(2).replace('.',',');
const s={wrap:{display:'grid',gap:20,background:'#FFF',borderRadius:24,padding:'22px 18px',boxShadow:'0 8px 28px rgba(67,42,34,.05)'},heading:{fontSize:20,fontWeight:850,margin:0,color:'#2D2724'},summary:{display:'grid',gap:7},row:{display:'flex',alignItems:'baseline',justifyContent:'space-between',gap:16,fontSize:17,color:'#332B28'},price:{fontSize:24,fontWeight:900,whiteSpace:'nowrap'},secondary:{fontSize:15,color:'#766862',fontWeight:600},methods:{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10},method:{minHeight:78,border:'1px solid #E6DEDA',borderRadius:18,background:'#FAF9F8',padding:'13px 14px',textAlign:'left',color:'#332B28',display:'grid',alignContent:'center',gap:3,cursor:'pointer'},selected:{border:'2px solid #8B1F24',background:'#FFF8F7',boxShadow:'0 0 0 2px rgba(139,31,36,.06)'},methodTop:{display:'flex',alignItems:'center',justifyContent:'space-between',gap:8,fontSize:17,fontWeight:850},methodMeta:{fontSize:15,color:'#766862',fontWeight:650},installmentTitle:{fontSize:17,fontWeight:850,color:'#332B28',margin:'2px 0 0'},installments:{display:'grid',gap:9},installment:{minHeight:62,width:'100%',display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,padding:'12px 14px',border:'1px solid #E6DEDA',borderRadius:16,background:'#FAF9F8',color:'#332B28',textAlign:'left',cursor:'pointer'},installmentMain:{fontSize:17,fontWeight:800},installmentTotal:{display:'block',fontSize:14,color:'#766862',marginTop:3},error:{background:'#FFF2F3',color:'#861D2E',borderRadius:14,padding:'12px 14px',fontSize:15,fontWeight:650},conflict:{background:'#FFF9F5',borderRadius:16,padding:14,color:'#554640'},cta:{minHeight:60,width:'100%',border:0,borderRadius:17,background:'#8B1F24',color:'#FFF',fontSize:17,fontWeight:900,letterSpacing:.2,cursor:'pointer'},ctaDisabled:{opacity:.45,cursor:'not-allowed'},spinner:{display:'inline-block',width:18,height:18,border:'2px solid rgba(255,255,255,.4)',borderTopColor:'#fff',borderRadius:'50%',animation:'m31Spin .7s linear infinite',verticalAlign:'-3px',marginRight:9},fallback:{textAlign:'center',color:'#8B1F24',fontWeight:750,fontSize:15}};
export default function ShirtSummaryBlock({itens,total,loading,error,pedidoConflitante,paymentUrl,paymentMethod,onPaymentMethod,installments,onInstallments,paymentQuote,cardQuotes={}}){
 const quote=paymentQuote||{total,installmentValue:total},displayTotal=paymentMethod==='CREDIT_CARD'?Number(quote.total||0):Number(total||0),hasItems=itens.length>0&&Number(total)>0;
 const options=[1,2,3,4,5].map(value=>({value,...(cardQuotes[value]||{})})).filter(o=>Number.isFinite(o.total)&&o.total>0);
 const ready=hasItems&&!!paymentMethod&&(paymentMethod!=='CREDIT_CARD'||displayTotal>0),qty=itens.length===1?'1 camisa':`${itens.length} camisas`;
 const payLine=paymentMethod==='PIX'?'PIX':paymentMethod==='CREDIT_CARD'&&displayTotal>0?`${installments}x de R$ ${brl(quote.installmentValue)}`:'📍 Retirada presencial';
 const cta=paymentMethod==='PIX'?'PAGAR COM PIX':paymentMethod==='CREDIT_CARD'&&displayTotal>0?`PAGAR R$ ${brl(displayTotal)}`:'PAGAR';
 return <section style={s.wrap}><style>{'@keyframes m31Spin{to{transform:rotate(360deg)}}'}</style>
  <div style={s.summary}><div style={s.row}><strong>{qty}</strong><span style={s.price}>R$ {brl(displayTotal||total)}</span></div><div style={s.secondary}>{payLine}</div></div>
  <div><h2 style={{...s.heading,marginBottom:12}}>Forma de pagamento</h2><div role="radiogroup" aria-label="Forma de pagamento" style={s.methods}>
   <button type="button" role="radio" aria-checked={paymentMethod==='PIX'} onClick={()=>onPaymentMethod('PIX')} style={{...s.method,...(paymentMethod==='PIX'?s.selected:{})}}><span style={s.methodTop}>PIX {paymentMethod==='PIX'&&<span>✓</span>}</span><span style={s.methodMeta}>R$ {brl(total)}</span></button>
   <button type="button" role="radio" aria-checked={paymentMethod==='CREDIT_CARD'} onClick={()=>onPaymentMethod('CREDIT_CARD')} style={{...s.method,...(paymentMethod==='CREDIT_CARD'?s.selected:{})}}><span style={s.methodTop}>CARTÃO {paymentMethod==='CREDIT_CARD'&&<span>✓</span>}</span><span style={s.methodMeta}>até 5x</span></button>
  </div></div>
  {paymentMethod==='CREDIT_CARD'&&<div style={s.installments}><h3 style={s.installmentTitle}>Escolha as parcelas</h3>{options.map(o=>{const active=Number(installments)===o.value,different=Math.abs(Number(o.total)-Number(total))>=.01;return <button key={o.value} type="button" role="radio" aria-checked={active} onClick={()=>onInstallments(o.value)} style={{...s.installment,...(active?s.selected:{})}}><span><span style={s.installmentMain}>{o.value}x de R$ {brl(o.installmentValue)}</span>{active&&different&&<span style={s.installmentTotal}>Total R$ {brl(o.total)}</span>}</span>{active&&<span style={{color:'#8B1F24',fontWeight:900}}>✓</span>}</button>})}</div>}
  {error&&<div role="alert" style={s.error}>{error}</div>}
  {pedidoConflitante&&<details style={s.conflict}><summary style={{fontWeight:800,cursor:'pointer'}}>Detalhes da compra</summary><div style={{marginTop:10}}><strong>Pedido original — R$ {brl(pedidoConflitante.valor_total)}</strong>{pedidoConflitante.itens.map((item,index)=><p key={index} style={{margin:'6px 0'}}>{nomeModelo(item)} · {item.tamanho}</p>)}</div></details>}
  {hasItems&&<><button type="submit" disabled={loading||!ready} style={{...s.cta,...((loading||!ready)?s.ctaDisabled:{})}} aria-busy={loading}>{loading?<><span style={s.spinner}/>PROCESSANDO...</>:cta}</button>{paymentUrl&&<a href={paymentUrl} style={s.fallback}>Abrir link de pagamento</a>}</>}
 </section>;
}
